google/tuneup.dart

lib/src/check_command.dart, lib/tuneup.dart, pubspec.yaml, test/integration_test.dart
=> make the 'check' command the default command

lib/src/check_command.dart, lib/src/common.dart, lib/tuneup.dart, pubspec.yaml
- rev the analyzer
- bump the tuneup version
Fix https://github.com/google/tuneup.dart/issues/26
=> rev the analyzer to 0.24.0

lib/src/check_command.dart, tool/travis.sh
- fix #32 (an issues when analyzing parts)
- run the tests and tuneup check in checked mode on the buildbot
=> fix a bug when analyzing parts

changelog.md, lib/src/check_command.dart, lib/src/common.dart, lib/tuneup.dart, pubspec.yaml
- added support for `.packages` files
- added support for SDK extensions
=> Ddc add sdk ext

changelog.md, lib/src/check_command.dart, lib/src/common.dart, lib/tuneup.dart, pubspec.yaml
- rev to the latest version of the analysis engine
- support conditional directives and super mixins
=> rev the analyzer version

changelog.md, lib/tuneup.dart, pubspec.yaml
- rev to the latest analyzer
- release v0.2.2
=> rev to the latest analyzer; 0.2.2

changelog.md, lib/src/check_command.dart, lib/tuneup.dart, pubspec.yaml
- upgrade the analyzer version
- remove use of deprecated methods
=> upgrade the analyzer version

changelog.md, lib/src/check_command.dart, lib/tuneup.dart, pubspec.yaml, test/common_test.dart, test/integration_test.dart
- rev to the latest analyzer version (`0.30.0-alpha.1`)
- move to testing using `unittest` to solve version lock issues
=> rev to the latest analyzer version

.analysis_options, lib/src/check_command.dart, lib/src/common.dart, lib/src/trim_command.dart, lib/tuneup.dart, pubspec.yaml, test/common_test.dart, test/integration_test.dart
- make strong
- remove `cli_util` references
- address todos
=> make strong; remove cli_util references; address todos

lib/src/analysis_server_lib.dart, lib/src/ansi.dart, lib/src/check_command.dart, pubspec.yaml, test/analysis_lib_test.dart, test/integration_test.dart, tool/analysis/analysis_tester.dart, tool/analysis/generate_analysis.dart
- improve the analysis server library examples
=> improve the analysis server library examples

lib/src/analysis_server_lib.dart, tool/analysis/generate_analysis.dart
Improvements to the analysis server library.
=> improvements to the analysis server library

changelog.md, lib/src/common.dart, lib/tuneup.dart, pubspec.yaml
- fix an npe w/ no pubspec
- fix https://github.com/google/tuneup.dart/issues/63
- rev the version to `0.3.1+1`
=> fix an npe w/ no pubspec

changelog.md, lib/commands/check.dart, lib/src/common.dart, lib/tuneup.dart, pubspec.yaml, tuneup.dart.iml
- add a --preview-dart-2 flag
- bump to `0.3.2` in prep for release
=> add a --preview-dart-2 flag

changelog.md, lib/commands/check.dart, lib/tuneup.dart, pubspec.yaml
- improved crash reporting
- bump to `0.3.2+2`
=> improved crash reporting

.gitignore, changelog.md, lib/commands/check.dart, lib/src/common.dart, lib/tuneup.dart, pubspec.yaml, test/integration_test.dart, tuneup.dart.iml
- update to the latest package deps
- prep for publishing `0.3.3`
=> update to the latest package deps

.travis.yml, analysis_options.yaml, changelog.md, lib/commands/check.dart, lib/commands/trim.dart, pubspec.yaml
- fix an issue with the --ignore-infos flag
- prep for `0.3.5`
=> fix an issue with the --ignore-infos flag

changelog.md, lib/tuneup.dart, pubspec.yaml, tool/travis.sh
- widen intl dep
- rev to new version for publish
- fix https://github.com/google/tuneup.dart/issues/78
=> widen dep; rev to new version for publish

changelog.md, lib/tuneup.dart, pubspec.yaml, test/integration_test.dart
- update the `package:cli_util` dep
- rev to 0.3.7
=> rev to 0.3.7

lib/tuneup.dart, pubspec.yaml
=> removed unused dart:async

lib/tuneup.dart, pubspec.yaml
- populate the `repository` field
- match the package version match
=> pubspec updates
